name: moneycoon
description: "부업앱 '머니쿤' 클론코딩"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  get_it: 7.0.0

  data:
    path: packages/data
  domain:
    path: packages/domain
  presentation:
    path: packages/presentation

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
